steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--no-cache',
    '--build-arg', 'VITE_SUPABASE_URL=$_VITE_SUPABASE_URL',
    '--build-arg', 'VITE_SUPABASE_ANON_KEY=$_VITE_SUPABASE_ANON_KEY',
    '--build-arg', 'VITE_USE_MOCK_AUTH=$_VITE_USE_MOCK_AUTH',
    '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME',
    '.'
  ]
images:
- 'gcr.io/$PROJECT_ID/$_SERVICE_NAME'
options:
  substitution_option: 'ALLOW_LOOSE'
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
